# 32. 31. componentDidCatch 와 Sentry 연동

: Sentry 란 우선적으로는 website 이름입니다.  
componentDidCatch 시 발생되는 에러를 연동하여 web상에서 확인 할수 있습니다.

[Sentry](https://sentry.io/welcome/)

[Sentry DOC](https://docs.sentry.io/)

build 후 개발서버 열기

```
npx serve ./build
```

## 예제코드

### index.js

```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

// yarn add @sentry/react @sentry/tracing

import * as Sentry from '@sentry/react';
import { Integrations } from '@sentry/tracing';

Sentry.init({
  dsn:
    'https://d40d60d691d14c3d9a47f2519721b58a@o461285.ingest.sentry.io/5462879',
  integrations: [new Integrations.BrowserTracing()],

  // We recommend adjusting this value in production, or using tracesSampler
  // for finer control
  tracesSampleRate: 1.0,
});

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root'),
);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
```

### App.js

```
import React from 'react';
import './App.css';
import User from './User';
import ErrorBoundary from './ErrorBoundary';

// build 후 개발서버 열기
// npx serve ./build

function App() {
  const user = {
    id: 1,
    username: 'park',
  };

  return (
    <ErrorBoundary>
      {/* ErrorBoundary 컴포넌트로 User 컴포넌트를 감싸는 이유는 */}
      {/* 에러 발생 예외처리를 ErrorBoundary 컴포넌트에서 진행중이고 */}
      {/* ErrorBoundary 안쪽에 있는 컴포넌트가 모두 랜더가 되어야 */}
      {/* /ErrorBoundary 로 인해 ErrorBoundary 컴포넌트도 랜더가 종료 됩니다. */}
      <User />
    </ErrorBoundary>
  );
}

export default App;
```

### ErrorBoundary.js

```
import React, { Component } from 'react';

import * as Sentry from '@sentry/react';
import { Integrations } from '@sentry/tracing';

class ErrorBoundary extends Component {
  state = {
    error: false,
  };

  componentDidCatch(error, info) {
    console.log('에러가 발생했습니다.');
    console.log({
      error,
      info,
    });
    this.setState({
      error: true,
    });

    // 개발서버는 상관 업지만
    // production 즉 build 가 된 상태하면 한가지 작업을 더 해주어야 합니다.
    // 아래와 같은 코드를 입력 합니다.
    if (process.env.NODE_ENV === 'production') {
      Sentry.captureException(error, { extra: info });
    }
  }

  render() {
    if (this.state.error) return <h1>에러 발생!</h1>;
    return this.props.children;
  }
}

/*
 <ErrorBoundary>
    <User />
 </ErrorBoundary>
*/
// ErrorBoundary 컴포넌트로 User 컴포넌트를 감싸는 이유는
// 에러 발생 예외처리를 ErrorBoundary 컴포넌트에서 진행중이고
// ErrorBoundary 안쪽에 있는 컴포넌트가 모두 랜더가 되어야
// /ErrorBoundary 로 인해 ErrorBoundary 컴포넌트도 랜더가 종료 됩니다.

export default ErrorBoundary;
```

### User.js

```
import React from 'react';

const User = ({ user }) => {
  //  if (!user) return null;
  // 기본적으로 코드에서 예외처리 해줌을 원칙으로 하지만...
  // 만약에 에러가 발생했다면... 개발자의 에러캐치와 사용자에게
  // 에러가 발생했음을 알려 주어야 합니다.

  // 에러의 원인 props으로 받아오는 user가 넘어오지 않아 에러 페이지가 나타나는데
  // 이는 개발서버에서 생성해주는 메시지 이며, 사용 자는 에러페이지 를 껏을때 나타나는
  // 빈 페이지만 보여 당황 스럽습니다.
  return (
    <div>
      <div>
        <b>ID</b>: {user.id}
      </div>
      <div>
        <b>Username</b>: {user.username}
      </div>
    </div>
  );
};

export default User;
```
